name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cl.exe /EHsc /LD /MT dllmain.cpp
      - uses: actions/upload-artifact@v4
        with:
          name: cheat-dll
          path: dllmain.dll
